sudo: required
language: python
services:
- docker
python:
- '2.7'
env:
- PATROWL_ENGINE="arachni" ENGINE_PORT=5105
- PATROWL_ENGINE="cortex" ENGINE_PORT=5009
- PATROWL_ENGINE="nessus" ENGINE_PORT=5002
- PATROWL_ENGINE="nmap" ENGINE_PORT=5001
- PATROWL_ENGINE="owl_code" ENGINE_PORT=5013
- PATROWL_ENGINE="owl_leaks" ENGINE_PORT=5012
- PATROWL_ENGINE="owl_dns" ENGINE_PORT=5006
- PATROWL_ENGINE="ssllabs" ENGINE_PORT=5004
- PATROWL_ENGINE="urlvoid" ENGINE_PORT=5008
- PATROWL_ENGINE="virustotal" ENGINE_PORT=5007
before_install:
- openssl aes-256-cbc -K $encrypted_e04b6597f270_key -iv $encrypted_e04b6597f270_iv
  -in virustotal.json.sample.enc -out virustotal.json.sample -d
- openssl aes-256-cbc -K $encrypted_e04b6597f270_key -iv $encrypted_e04b6597f270_iv
  -in virustotal.json.enc -out virustotal.json -d
- cd engines/$PATROWL_ENGINE
install:
- pip install -r requirements.txt
- pip install requests
script:
- gunicorn engine-$PATROWL_ENGINE:app -b 0.0.0.0:1$ENGINE_PORT > /dev/null &
- docker --version
- docker build --tag docker_$PATROWL_ENGINE .
- docker run -d --rm -p $ENGINE_PORT:$ENGINE_PORT docker_$PATROWL_ENGINE
- docker ps -a
- pytest -s ./tests/*
after_script:
- docker images
