sudo: required

language: python

services:
  - docker

python:
  - "2.7"
  # - "3.5"

env:
  - PATROWL_ENGINE="arachni" ENGINE_PORT=5105
  # - PATROWL_ENGINE="burp"
  # - PATROWL_ENGINE="censys"
  - PATROWL_ENGINE="cortex" ENGINE_PORT=5009
  - PATROWL_ENGINE="nessus" ENGINE_PORT=5002
  - PATROWL_ENGINE="nmap" ENGINE_PORT=5001
  - PATROWL_ENGINE="owl_code" ENGINE_PORT=5013
  - PATROWL_ENGINE="owl_leaks" ENGINE_PORT=5012
  - PATROWL_ENGINE="owl_dns" ENGINE_PORT=5006
  - PATROWL_ENGINE="ssllabs" ENGINE_PORT=5004
  - PATROWL_ENGINE="urlvoid" ENGINE_PORT=5008
  - PATROWL_ENGINE="virustotal" ENGINE_PORT=5007

before_install:
  - cd engines/$PATROWL_ENGINE

install:
  - pip install -r requirements.txt
  - pip install requests

script:
  # - python engine-$PATROWL_ENGINE.py > /dev/null &
  # Run the inst
  - gunicorn engine-$PATROWL_ENGINE:app -b 0.0.0.0:$ENGINE_PORT > /dev/null &

  # Build and run the docker image
  - docker --version
  - docker build --tag docker_$PATROWL_ENGINE .
  - docker run --rm -d docker_$PATROWL_ENGINE
  - docker ps -a
  # Perform tests on the docker instance
  - pytest -s $PATROWL_ENGINE/tests/*

after_script:
  - docker images
