sudo: enabled

language: python

services:
  - docker

python:
  - "2.7"

env:
  - PATROWL_ENGINE="arachni"
  # - PATROWL_ENGINE="burp"
  - PATROWL_ENGINE="censys"
  - PATROWL_ENGINE="cortex"
  - PATROWL_ENGINE="nessus"
  - PATROWL_ENGINE="nmap"
  - PATROWL_ENGINE="owl_code"
  - PATROWL_ENGINE="owl_dns"
  - PATROWL_ENGINE="ssllabs"
  - PATROWL_ENGINE="urlvoid"
  - PATROWL_ENGINE="virustotal"

before_install:
  - cd engines/$PATROWL_ENGINE

install:
  - pip install -r requirements.txt
  - pip install requests

script:
  - python engine-$PATROWL_ENGINE.py -d > /dev/null &
  - pytest
  - docker build --tag docker_$PATROWL_ENGINE .
  - docker run docker_$PATROWL_ENGINE

after_script:
  - docker images
